module.exports = {
	propsParser: require('react-docgen-typescript').parse,
	ignore: [
		'**/*.spec.js',
		'**/components/Sidebar.tsx',
		'**/components/Board.tsx',
		'**/components/CreateGroup.tsx',
		'**/components/CreateListItem.tsx',
		'**/components/MainList/MainList.tsx',
		'**/components/ContextualMenu/ContextualMenuItem.tsx',
		'**/components/Tooltip/Tooltip.tsx',
		'**/components/Toolbar.tsx',
		'**/components/Tasks/useTask.tsx',
		'**/components/Tasks/useIncompleteCompleteTasks.ts',
		'**/components/Tasks/TaskSidebarDetailsContainer.tsx',
		'**/components/Tasks/TaskItem/TaskItem.tsx',
		'**/components/Tasks/InCompletedTasks.tsx',
		'**/components/Tasks/CreateTask.tsx',
		'**/components/Tasks/ComplitedTasks.tsx',
		'**/components/SortComponent/SortComponent.tsx',
		'**/components/MainList/useMainList.ts',
		'**/components/Loader/Loader.tsx',
		'**/components/List/useList.ts',
		'**/components/List/Lists/Lists.tsx',
		'**/components/List/CreateList/CreateList.tsx',
		'**/components/Header.tsx',
		'**/components/Tasks/Tasks.tsx',
	],
};
